//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.ApplicationCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.ApplicationCop.ApplicationCopAnalyzers", typeof(ApplicationCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ConfirmImplementConfirmManagementDescription {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor to use &quot;Confirm Management&quot; codeunit.
        /// </summary>
        internal static string ConfirmImplementConfirmManagementDescriptionCodeAction {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementDescriptionCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm() must be implemented through the &quot;Confirm Management&quot; codeunit from the System Application..
        /// </summary>
        internal static string ConfirmImplementConfirmManagementMessageFormat {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm() must be implemented through the &quot;Confirm Management&quot; codeunit.
        /// </summary>
        internal static string ConfirmImplementConfirmManagementTitle {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor to use &quot;Translation Helper&quot; codeunit.
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperCodeAction {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperDescription {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalLanguage() must be implemented through the &quot;Translation Helper&quot; codeunit from the Base Application..
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperMessageFormat {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalLanguage() must be implemented through the &quot;Translation Helper&quot; codeunit..
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperTitle {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a table is used as the source for a list page, users expect to be able to drill down into records and open lookups in a consistent and predictable way. The DrillDownPageId and LookupPageId table properties define which pages are used for these interactions..
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdDescription {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; is used in a list page but does not define both the DrillDownPageId and LookupPageId properties..
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdMessageFormat {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrillDownPageId and LookupPageId property must be defined for tables used in list pages.
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdTitle {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set NotBlank property to false.
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldCodeAction {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the &apos;No. Series&apos; TableRelation is present on the table, assigning the primary key might occur after inserting the record, which could cause an error due to the NotBlank property..
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldDescription {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotBlank property should be set to false (or removed) if a TableRelation of &apos;No. Series&apos; is present on the table..
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldMessageFormat {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set NotBlank property to false when &apos;No. Series&apos; TableRelation exists.
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldTitle {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set NotBlank property to true.
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldCodeAction {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In tables that define a primary key consisting of a single field of type Code or Text, the primary key field must explicitly set the NotBlank property..
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldDescription {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBlank property should be set explicitly for tables with a single-field primary key..
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldMessageFormat {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-field primary key requires the NotBlank property.
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldTitle {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: X.
        /// </summary>
        internal static string RunPageImplementPageManagementCodeAction {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string RunPageImplementPageManagementDescription {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string RunPageImplementPageManagementMessageFormat {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string RunPageImplementPageManagementTitle {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementTitle", resourceCulture);
            }
        }
    }
}
