//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.ApplicationCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.ApplicationCop.ApplicationCopAnalyzers", typeof(ApplicationCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All user-facing application objects and controls must explicitly define a Caption to ensure a consistent, accessible, and localizable user interface..
        /// </summary>
        internal static string CaptionRequiredDescription {
            get {
                return ResourceManager.GetString("CaptionRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user-facing object or control is missing a Caption..
        /// </summary>
        internal static string CaptionRequiredMessageFormat {
            get {
                return ResourceManager.GetString("CaptionRequiredMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captions must be defined on user-facing objects and controls.
        /// </summary>
        internal static string CaptionRequiredTitle {
            get {
                return ResourceManager.GetString("CaptionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct calls to Confirm() bypass the safeguards and features provided by the Confirm Management codeunit in the System Application. Using Confirm Management ensures automatic validation of IsGuiAllowed(), prevents runtime failures in non-GUI contexts, and allows explicit control over the default response (true or false)..
        /// </summary>
        internal static string ConfirmImplementConfirmManagementDescription {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor to use &quot;Confirm Management&quot; codeunit.
        /// </summary>
        internal static string ConfirmImplementConfirmManagementDescriptionCodeAction {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementDescriptionCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm() must be implemented through the &quot;Confirm Management&quot; codeunit from the System Application..
        /// </summary>
        internal static string ConfirmImplementConfirmManagementMessageFormat {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm() must be implemented through the &quot;Confirm Management&quot; codeunit.
        /// </summary>
        internal static string ConfirmImplementConfirmManagementTitle {
            get {
                return ResourceManager.GetString("ConfirmImplementConfirmManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table objects must explicitly define both the DropDown and Brick fieldgroups..
        /// </summary>
        internal static string FieldGroupsRequiredDescription {
            get {
                return ResourceManager.GetString("FieldGroupsRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; is missing the required &apos;{1}&apos; fieldgroup..
        /// </summary>
        internal static string FieldGroupsRequiredMessageFormat {
            get {
                return ResourceManager.GetString("FieldGroupsRequiredMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDown and Brick fieldgroups must be defined.
        /// </summary>
        internal static string FieldGroupsRequiredTitle {
            get {
                return ResourceManager.GetString("FieldGroupsRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor to use &quot;Translation Helper&quot; codeunit.
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperCodeAction {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct use of GlobalLanguage() leads to verbose, error-prone code and often requires manual state management, hardcoded language IDs, or duplicated logic. The Translation Helper codeunit from the Base Application centralizes global language handling by automatically preserving and restoring the previous language, supporting both LanguageId and LanguageCode, and allowing a safe reset to the default application language without hardcoding values such as 1033..
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperDescription {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalLanguage() must be implemented through the &quot;Translation Helper&quot; codeunit from the Base Application..
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperMessageFormat {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalLanguage() must be implemented through the &quot;Translation Helper&quot; codeunit.
        /// </summary>
        internal static string GlobalLanguageImplementTranslationHelperTitle {
            get {
                return ResourceManager.GetString("GlobalLanguageImplementTranslationHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Access property to Internal.
        /// </summary>
        internal static string InstallAndUpgradeCodeunitsShouldBeInternalCodeAction {
            get {
                return ResourceManager.GetString("InstallAndUpgradeCodeunitsShouldBeInternalCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and Upgrade codeunits are intended for lifecycle execution only and are not designed to expose reusable APIs. Declaring them as Public unnecessarily broadens their surface area and increases coupling between extensions..
        /// </summary>
        internal static string InstallAndUpgradeCodeunitsShouldBeInternalDescription {
            get {
                return ResourceManager.GetString("InstallAndUpgradeCodeunitsShouldBeInternalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Access property to Internal for Install and Upgrade codeunits..
        /// </summary>
        internal static string InstallAndUpgradeCodeunitsShouldBeInternalMessageFormat {
            get {
                return ResourceManager.GetString("InstallAndUpgradeCodeunitsShouldBeInternalMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and Upgrade codeunits should have Access set to Internal.
        /// </summary>
        internal static string InstallAndUpgradeCodeunitsShouldBeInternalTitle {
            get {
                return ResourceManager.GetString("InstallAndUpgradeCodeunitsShouldBeInternalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor from IntegrationEvent to InternalEvent.
        /// </summary>
        internal static string IntegrationEventInInternalCodeunitChangeToInternalEventCodeAction {
            get {
                return ResourceManager.GetString("IntegrationEventInInternalCodeunitChangeToInternalEventCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration events are designed to be consumed by extensions and therefore must be accessible outside the defining app. When an IntegrationEvent is declared in a codeunit with Access = Internal, the event cannot be subscribed to by extensions, rendering it ineffective..
        /// </summary>
        internal static string IntegrationEventInInternalCodeunitDescription {
            get {
                return ResourceManager.GetString("IntegrationEventInInternalCodeunitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration event &apos;{0}&apos; is declared in a codeunit with Access = Interna`, making it inaccessible to extensions. Remove the Access property or declare the event as an InternalEvent..
        /// </summary>
        internal static string IntegrationEventInInternalCodeunitMessageFormat {
            get {
                return ResourceManager.GetString("IntegrationEventInInternalCodeunitMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove property Access = Internal.
        /// </summary>
        internal static string IntegrationEventInInternalCodeunitRemoveAccessPropertyCodeAction {
            get {
                return ResourceManager.GetString("IntegrationEventInInternalCodeunitRemoveAccessPropertyCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration events must not be declared in codeunits with Access set to Internal.
        /// </summary>
        internal static string IntegrationEventInInternalCodeunitTitle {
            get {
                return ResourceManager.GetString("IntegrationEventInInternalCodeunitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a table is used as the source for a list page, users expect to be able to drill down into records and open lookups in a consistent and predictable way. The DrillDownPageId and LookupPageId table properties define which pages are used for these interactions..
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdDescription {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; is used in a list page but does not define both the DrillDownPageId and LookupPageId properties..
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdMessageFormat {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrillDownPageId and LookupPageId property must be defined for tables used in list pages.
        /// </summary>
        internal static string LookupPageIdAndDrillDownPageIdTitle {
            get {
                return ResourceManager.GetString("LookupPageIdAndDrillDownPageIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set NotBlank property to false.
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldCodeAction {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the &apos;No. Series&apos; TableRelation is present on the table, assigning the primary key might occur after inserting the record, which could cause an error due to the NotBlank property..
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldDescription {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotBlank property should be set to false (or removed) if a TableRelation of &apos;No. Series&apos; is present on the table..
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldMessageFormat {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set NotBlank property to false when &apos;No. Series&apos; TableRelation exists.
        /// </summary>
        internal static string NotBlankNotAllowedOnPrimaryKeyFieldTitle {
            get {
                return ResourceManager.GetString("NotBlankNotAllowedOnPrimaryKeyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set NotBlank property to true.
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldCodeAction {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In tables that define a primary key consisting of a single field of type Code or Text, the primary key field must explicitly set the NotBlank property..
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldDescription {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBlank property should be set explicitly for tables with a single-field primary key..
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldMessageFormat {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-field primary key requires the NotBlank property.
        /// </summary>
        internal static string NotBlankRequiredOnPrimaryKeyFieldTitle {
            get {
                return ResourceManager.GetString("NotBlankRequiredOnPrimaryKeyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set MaxLength property to 30.
        /// </summary>
        internal static string PermissionSetCaptionLengthCodeAction {
            get {
                return ResourceManager.GetString("PermissionSetCaptionLengthCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionSet captions should remain within a defined maximum length to avoid issues in translated captions. When no MaxLength or Locked subproperty is specified, translations can exceed the intended limit and cause inconsistent or truncated UI labels..
        /// </summary>
        internal static string PermissionSetCaptionLengthDescription {
            get {
                return ResourceManager.GetString("PermissionSetCaptionLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Caption of permissionset objects should not exceed {0} characters. Use MaxLength={0} or Locked=true to ensure there are no translations that exceed this limit..
        /// </summary>
        internal static string PermissionSetCaptionLengthMessageFormat {
            get {
                return ResourceManager.GetString("PermissionSetCaptionLengthMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Caption of permissionset objects should not exceed the maximum length.
        /// </summary>
        internal static string PermissionSetCaptionLengthTitle {
            get {
                return ResourceManager.GetString("PermissionSetCaptionLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every application object in an extension must be explicitly granted permissions through at least one permission set or permission set extension, defined in AL or XML..
        /// </summary>
        internal static string PermissionSetCoverageDescription {
            get {
                return ResourceManager.GetString("PermissionSetCoverageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application object {0} &apos;{1}&apos; is not covered by any PermissionSet in this extension..
        /// </summary>
        internal static string PermissionSetCoverageMessageFormat {
            get {
                return ResourceManager.GetString("PermissionSetCoverageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All application objects must be covered by a PermissionSet.
        /// </summary>
        internal static string PermissionSetCoverageTitle {
            get {
                return ResourceManager.GetString("PermissionSetCoverageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor to use &quot;Page Management&quot; codeunit.
        /// </summary>
        internal static string RunPageImplementPageManagementCodeAction {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct calls to Page.Run bypass the centralized logic provided by the Page Management codeunit. Using Page Management improves correctness and extensibility by automatically resolving the appropriate page..
        /// </summary>
        internal static string RunPageImplementPageManagementDescription {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke pages through the &quot;Page Management&quot; codeunit instead of invoking Page.Run(...) directly for this record context..
        /// </summary>
        internal static string RunPageImplementPageManagementMessageFormat {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &quot;Page Management&quot; codeunit instead invoking Page.Run directly.
        /// </summary>
        internal static string RunPageImplementPageManagementTitle {
            get {
                return ResourceManager.GetString("RunPageImplementPageManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In projects where company data isolation matters, table objects must explicitly define the DataPerCompany property. Relying on implicit defaults makes the data scope unclear and can lead to incorrect assumptions about whether data is shared across companies or stored per company..
        /// </summary>
        internal static string TableDataPerCompanyDeclarationDescription {
            get {
                return ResourceManager.GetString("TableDataPerCompanyDeclarationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table object does not explicitly define the DataPerCompany property..
        /// </summary>
        internal static string TableDataPerCompanyDeclarationMessageFormat {
            get {
                return ResourceManager.GetString("TableDataPerCompanyDeclarationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPerCompany must be explicitly set on table objects.
        /// </summary>
        internal static string TableDataPerCompanyDeclarationTitle {
            get {
                return ResourceManager.GetString("TableDataPerCompanyDeclarationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Business Central user assistance model does not support formatting in ToolTips. Line breaks are not rendered and make the ToolTip harder to read. Keep ToolTips as a single, continuous sentence..
        /// </summary>
        internal static string ToolTipDoNotUseLineBreaksDescription {
            get {
                return ResourceManager.GetString("ToolTipDoNotUseLineBreaksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip text must not contain line breaks..
        /// </summary>
        internal static string ToolTipDoNotUseLineBreaksMessageFormat {
            get {
                return ResourceManager.GetString("ToolTipDoNotUseLineBreaksMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use line breaks in ToolTip.
        /// </summary>
        internal static string ToolTipDoNotUseLineBreaksTitle {
            get {
                return ResourceManager.GetString("ToolTipDoNotUseLineBreaksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user assistance model recommends keeping ToolTips short (about 200 characters including spaces) so users can scan them quickly. The UI can render longer ToolTips, but longer text reduces scannability and consistency..
        /// </summary>
        internal static string ToolTipMaximumLengthDescription {
            get {
                return ResourceManager.GetString("ToolTipMaximumLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip exceeds the recommended maximum length of 200 characters..
        /// </summary>
        internal static string ToolTipMaximumLengthMessageFormat {
            get {
                return ResourceManager.GetString("ToolTipMaximumLengthMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip should not exceed 200 characters.
        /// </summary>
        internal static string ToolTipMaximumLengthTitle {
            get {
                return ResourceManager.GetString("ToolTipMaximumLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End ToolTips with a dot to keep phrasing consistent and clearly separated from surrounding UI text..
        /// </summary>
        internal static string ToolTipMustEndWithDotDescription {
            get {
                return ResourceManager.GetString("ToolTipMustEndWithDotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip must end with a dot..
        /// </summary>
        internal static string ToolTipMustEndWithDotMessageFormat {
            get {
                return ResourceManager.GetString("ToolTipMustEndWithDotMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip must end with a dot.
        /// </summary>
        internal static string ToolTipMustEndWithDotTitle {
            get {
                return ResourceManager.GetString("ToolTipMustEndWithDotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For field ToolTips, the Business Central user assistance model expects the text to start with the verb &apos;Specifies&apos; to describe what the field represents..
        /// </summary>
        internal static string ToolTipShouldStartWithSpecifiesDescription {
            get {
                return ResourceManager.GetString("ToolTipShouldStartWithSpecifiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip should start with the verb &apos;Specifies&apos;..
        /// </summary>
        internal static string ToolTipShouldStartWithSpecifiesMessageFormat {
            get {
                return ResourceManager.GetString("ToolTipShouldStartWithSpecifiesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip should start with &apos;Specifies&apos;.
        /// </summary>
        internal static string ToolTipShouldStartWithSpecifiesTitle {
            get {
                return ResourceManager.GetString("ToolTipShouldStartWithSpecifiesTitle", resourceCulture);
            }
        }
    }
}
