//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.LinterCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinterCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinterCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.LinterCop.LinterCopAnalyzers", typeof(LinterCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports the cyclomatic complexity of a method or trigger. Cyclomatic complexity represents the number of independent execution paths through the code and provides insight into control-flow complexity..
        /// </summary>
        internal static string CyclomaticComplexityMetricDescription {
            get {
                return ResourceManager.GetString("CyclomaticComplexityMetricDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity: {0} (threshold ≥ {1}).
        /// </summary>
        internal static string CyclomaticComplexityMetricMessageFormat {
            get {
                return ResourceManager.GetString("CyclomaticComplexityMetricMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity metric.
        /// </summary>
        internal static string CyclomaticComplexityMetricTitle {
            get {
                return ResourceManager.GetString("CyclomaticComplexityMetricTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity measures the number of independent execution paths through a method or trigger. When this value meets or exceeds the configured threshold, the code is considered overly complex, which can reduce readability, increase maintenance cost, and raise the risk of defects..
        /// </summary>
        internal static string CyclomaticComplexityThresholdExceededDescription {
            get {
                return ResourceManager.GetString("CyclomaticComplexityThresholdExceededDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity: {0} (threshold ≥ {1}).
        /// </summary>
        internal static string CyclomaticComplexityThresholdExceededMessageFormat {
            get {
                return ResourceManager.GetString("CyclomaticComplexityThresholdExceededMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity exceeds configured threshold.
        /// </summary>
        internal static string CyclomaticComplexityThresholdExceededTitle {
            get {
                return ResourceManager.GetString("CyclomaticComplexityThresholdExceededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports the maintainability index of a method or trigger. The maintainability index is a composite metric derived from cyclomatic complexity, Halstead volume, and code size, providing an overall indication of how easy the code is to understand, modify, and maintain..
        /// </summary>
        internal static string MaintainabilityIndexMetricDescription {
            get {
                return ResourceManager.GetString("MaintainabilityIndexMetricDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability index: {0} (threshold ≤ {1}).
        /// </summary>
        internal static string MaintainabilityIndexMetricMessageFormat {
            get {
                return ResourceManager.GetString("MaintainabilityIndexMetricMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability index metric.
        /// </summary>
        internal static string MaintainabilityIndexMetricTitle {
            get {
                return ResourceManager.GetString("MaintainabilityIndexMetricTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maintainability index provides an overall indication of code maintainability based on complexity, size, and structural characteristics. When this value falls at or below the configured threshold, the code is considered difficult to maintain, increasing the likelihood of defects and long-term maintenance cost..
        /// </summary>
        internal static string MaintainabilityIndexThresholdExceededDescription {
            get {
                return ResourceManager.GetString("MaintainabilityIndexThresholdExceededDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability index: {0} (threshold ≤ {1}).
        /// </summary>
        internal static string MaintainabilityIndexThresholdExceededMessageFormat {
            get {
                return ResourceManager.GetString("MaintainabilityIndexThresholdExceededMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability index below configured threshold.
        /// </summary>
        internal static string MaintainabilityIndexThresholdExceededTitle {
            get {
                return ResourceManager.GetString("MaintainabilityIndexThresholdExceededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace id with name of object reference.
        /// </summary>
        internal static string ObjectIdInDeclarationActionTitle {
            get {
                return ResourceManager.GetString("ObjectIdInDeclarationActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Object IDs in variable or property declarations reduces readability and prevents safe renaming. Object IDs are numeric and provide no semantic meaning, making the code harder to understand and maintain. Declare variables and properties using the resolved object name rather than a numeric Object ID..
        /// </summary>
        internal static string ObjectIdInDeclarationDescription {
            get {
                return ResourceManager.GetString("ObjectIdInDeclarationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID &apos;{0}&apos; used as object reference..
        /// </summary>
        internal static string ObjectIdInDeclarationFormatWithoutCodeFix {
            get {
                return ResourceManager.GetString("ObjectIdInDeclarationFormatWithoutCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID &apos;{0}&apos; used as object reference. Use the object name &apos;{1}&apos; instead..
        /// </summary>
        internal static string ObjectIdInDeclarationMessageFormat {
            get {
                return ResourceManager.GetString("ObjectIdInDeclarationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use Object IDs as object references.
        /// </summary>
        internal static string ObjectIdInDeclarationTitle {
            get {
                return ResourceManager.GetString("ObjectIdInDeclarationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace LockTable() with ReadIsolation.
        /// </summary>
        internal static string RecordInstanceIsolationLevelCodeActionTitle {
            get {
                return ResourceManager.GetString("RecordInstanceIsolationLevelCodeActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the ReadIsolation method to control isolation level on database transactions instead of the LockTable method..
        /// </summary>
        internal static string RecordInstanceIsolationLevelDescription {
            get {
                return ResourceManager.GetString("RecordInstanceIsolationLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ReadIsolation(IsolationLevel::UpdLock) instead of LockTable()..
        /// </summary>
        internal static string RecordInstanceIsolationLevelMessageFormat {
            get {
                return ResourceManager.GetString("RecordInstanceIsolationLevelMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ReadIsolation instead of LockTable.
        /// </summary>
        internal static string RecordInstanceIsolationLevelTitle {
            get {
                return ResourceManager.GetString("RecordInstanceIsolationLevelTitle", resourceCulture);
            }
        }
    }
}
