//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.PlatformCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlatformCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.PlatformCop.PlatformCopAnalyzers", typeof(PlatformCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement relies on SQL Server to generate the next value when inserting records. Temporary tables are only in-memory in Business Central and are not created on SQL Server, so SQL Server cannot generate AutoIncrement values. This results in runtime failures when code inserts into the temporary table..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableDescription {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement is used in a table with TableType = Temporary, which will cause a runtime error. Remove AutoIncrement or make the table non-temporary..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableMessageFormat {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement fields are not supported in temporary tables.
        /// </summary>
        internal static string AutoIncrementInTemporaryTableTitle {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Editable property to false.
        /// </summary>
        internal static string EditableFlowFieldCodeAction {
            get {
                return ResourceManager.GetString("EditableFlowFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields are calculated fields whose values are derived from other data and are not stored on the record itself. Allowing a FlowField to be editable exposes an input surface that the platform does not process by default. User-entered values are neither validated nor persisted unless custom logic is explicitly implemented..
        /// </summary>
        internal static string EditableFlowFieldDescription {
            get {
                return ResourceManager.GetString("EditableFlowFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is editable, which is uncommon for a FlowField. Set Editable = false, or add a comment to justify why editing is intentional..
        /// </summary>
        internal static string EditableFlowFieldMessageFormat {
            get {
                return ResourceManager.GetString("EditableFlowFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable.
        /// </summary>
        internal static string EditableFlowFieldTitle {
            get {
                return ResourceManager.GetString("EditableFlowFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace SetRange with SetFilter.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsCodeAction {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is intended for simple value-based range filtering. When filter operators such as &lt;&gt;, .., *, &amp;, or | are used, the call represents a filter expression and may lead to unintended behavior. In such cases, SetFilter must be used to express the filter explicitly and correctly..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsDescription {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is called with a filter expression. Use SetFilter instead..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsMessageFormat {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter operators should not be used in SetRange.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsTitle {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsTitle", resourceCulture);
            }
        }
    }
}
