//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.PlatformCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlatformCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.PlatformCop.PlatformCopAnalyzers", typeof(PlatformCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every AL object should explicitly specify its Access property to make its intended accessibility clear. Explicitly setting Access prevents accidental exposure or over-restriction of objects and forces conscious design decisions about visibility..
        /// </summary>
        internal static string AccessPropertyExplicitlySetDescription {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; does not explicitly have the Access property set..
        /// </summary>
        internal static string AccessPropertyExplicitlySetMessageFormat {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every object needs to specify a value for the Access property.
        /// </summary>
        internal static string AccessPropertyExplicitlySetTitle {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Remove &apos;ApplicationArea&apos; property.
        /// </summary>
        internal static string ApplicationAreaOnApiPageCodeAction {
            get {
                return ResourceManager.GetString("ApplicationAreaOnApiPageCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ApplicationArea property has no effect on API pages. API pages are consumed programmatically and do not participate in the user interface personalization model. Keeping this property on API pages adds noise without functional value and should be removed to keep the code clean..
        /// </summary>
        internal static string ApplicationAreaOnApiPageDescription {
            get {
                return ResourceManager.GetString("ApplicationAreaOnApiPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ApplicationArea&apos; property is not applicable to API pages and should be removed..
        /// </summary>
        internal static string ApplicationAreaOnApiPageMessageFormat {
            get {
                return ResourceManager.GetString("ApplicationAreaOnApiPageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ApplicationArea&apos; property is not applicable to API pages..
        /// </summary>
        internal static string ApplicationAreaOnApiPageTitle {
            get {
                return ResourceManager.GetString("ApplicationAreaOnApiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoCalcFields should only be used for FlowFields or Blob fields.
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsDescription {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AutoCalcFields method should only be used with FlowFields or fields of type Blob. The field {0} is not a FlowField or of type Blob..
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsMessageFormat {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoids a runtime error from using AutoCalcFields on a field that is not a FlowField or a field of type Blob..
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsTitle {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement relies on SQL Server to generate the next value when inserting records. Temporary tables are only in-memory in Business Central and are not created on SQL Server, so SQL Server cannot generate AutoIncrement values. This results in runtime failures when code inserts into the temporary table..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableDescription {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement is used in a table with TableType = Temporary, which will cause a runtime error. Remove AutoIncrement or make the table non-temporary..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableMessageFormat {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement fields are not supported in temporary tables.
        /// </summary>
        internal static string AutoIncrementInTemporaryTableTitle {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleInstance codeunits keep their global (state) variables for the lifetime of the session. Calling Clear() on a SingleInstance codeunit variable, or calling ClearAll() in an object that contains local/global SingleInstance codeunit variables, does not reset the stored global values inside those SingleInstance codeunits..
        /// </summary>
        internal static string ClearCodeunitSingleInstanceDescription {
            get {
                return ResourceManager.GetString("ClearCodeunitSingleInstanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear(All) does not affect or change values for global variables in &apos;{0}: Codeunit {1}&apos;..
        /// </summary>
        internal static string ClearCodeunitSingleInstanceMessageFormat {
            get {
                return ResourceManager.GetString("ClearCodeunitSingleInstanceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear/ClearAll does not reset SingleInstance codeunit state.
        /// </summary>
        internal static string ClearCodeunitSingleInstanceTitle {
            get {
                return ResourceManager.GetString("ClearCodeunitSingleInstanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Editable property to False.
        /// </summary>
        internal static string EditableFlowFieldCodeAction {
            get {
                return ResourceManager.GetString("EditableFlowFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields are calculated fields whose values are derived from other data and are not stored on the record itself. Allowing a FlowField to be editable exposes an input surface that the platform does not process by default. User-entered values are neither validated nor persisted unless custom logic is explicitly implemented..
        /// </summary>
        internal static string EditableFlowFieldDescription {
            get {
                return ResourceManager.GetString("EditableFlowFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is editable, which is uncommon for a FlowField. Set Editable = false, or add a comment to justify why editing is intentional..
        /// </summary>
        internal static string EditableFlowFieldMessageFormat {
            get {
                return ResourceManager.GetString("EditableFlowFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable.
        /// </summary>
        internal static string EditableFlowFieldTitle {
            get {
                return ResourceManager.GetString("EditableFlowFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Add var keyword.
        /// </summary>
        internal static string EventPublisherIsHandledByVarCodeAction {
            get {
                return ResourceManager.GetString("EventPublisherIsHandledByVarCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies event parameters of type boolean named IsHandled or Handled that are not passed by var..
        /// </summary>
        internal static string EventPublisherIsHandledByVarDescription {
            get {
                return ResourceManager.GetString("EventPublisherIsHandledByVarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must use the &apos;var&apos; keyword if the publisher parameter is &apos;var&apos;..
        /// </summary>
        internal static string EventPublisherIsHandledByVarMessageFormat {
            get {
                return ResourceManager.GetString("EventPublisherIsHandledByVarMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled parameters in event signatures should be passed by var.
        /// </summary>
        internal static string EventPublisherIsHandledByVarTitle {
            get {
                return ResourceManager.GetString("EventPublisherIsHandledByVarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Add var keyword.
        /// </summary>
        internal static string EventSubscriberVarKeywordCodeAction {
            get {
                return ResourceManager.GetString("EventSubscriberVarKeywordCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensures that event subscriber methods use &apos;var&apos; keyword for parameters as defined by event publisher..
        /// </summary>
        internal static string EventSubscriberVarKeywordDescription {
            get {
                return ResourceManager.GetString("EventSubscriberVarKeywordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must use the &apos;var&apos; keyword if the publisher parameter is &apos;var&apos;..
        /// </summary>
        internal static string EventSubscriberVarKeywordMessageFormat {
            get {
                return ResourceManager.GetString("EventSubscriberVarKeywordMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event subscriber var keyword mismatch..
        /// </summary>
        internal static string EventSubscriberVarKeywordTitle {
            get {
                return ResourceManager.GetString("EventSubscriberVarKeywordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Extensible property to platform default.
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetCodeAction {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public objects should explicitly define their extensibility by setting the Extensible property to either true or false. Leaving this property unspecified relies on implicit defaults and can lead to avoidable compatibility and maintenance issues..
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetDescription {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property Extensible should be explicitly set for public objects..
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetMessageFormat {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicitly set Extensible property on public objects.
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetTitle {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Fix single-quote escaping in filter string.
        /// </summary>
        internal static string FilterStringSingleQuoteEscapingCodeAction {
            get {
                return ResourceManager.GetString("FilterStringSingleQuoteEscapingCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filter string representing an is-not-empty condition is incorrectly escaped..
        /// </summary>
        internal static string FilterStringSingleQuoteEscapingDescription {
            get {
                return ResourceManager.GetString("FilterStringSingleQuoteEscapingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter string {0} uses incorrect single-quote escaping for a not-empty filter..
        /// </summary>
        internal static string FilterStringSingleQuoteEscapingMessageFormat {
            get {
                return ResourceManager.GetString("FilterStringSingleQuoteEscapingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid single-quote escaping in filter string.
        /// </summary>
        internal static string FilterStringSingleQuoteEscapingTitle {
            get {
                return ResourceManager.GetString("FilterStringSingleQuoteEscapingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly assigning values to FlowFilter fields bypasses their purpose and invalidates the filtering logic, resulting in incorrect or unintended calculations. Instead, use the .SetFilter() or .SetRange() methods to define the appropriate filters..
        /// </summary>
        internal static string FlowFilterFieldAssignmentDescription {
            get {
                return ResourceManager.GetString("FlowFilterFieldAssignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct assignment to the &apos;{0}&apos; field of type FlowFilter invalidates the filter logic for calculations. Use .SetFilter() or .SetRange() to set the filter correctly..
        /// </summary>
        internal static string FlowFilterFieldAssignmentMessageFormat {
            get {
                return ResourceManager.GetString("FlowFilterFieldAssignmentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set values for FlowFilter fields using filtering methods.
        /// </summary>
        internal static string FlowFilterFieldAssignmentTitle {
            get {
                return ResourceManager.GetString("FlowFilterFieldAssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Use IsNullGuid().
        /// </summary>
        internal static string GuidEmptyStringComparisonCodeAction {
            get {
                return ResourceManager.GetString("GuidEmptyStringComparisonCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checking if a GUID is empty, avoid using direct comparisons such as MyGuid = &apos;&apos;, as this will result in a runtime error due to the invalid GUID format. Instead, use the IsNullGuid() method to perform the check safely and correctly..
        /// </summary>
        internal static string GuidEmptyStringComparisonDescription {
            get {
                return ResourceManager.GetString("GuidEmptyStringComparisonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;IsNullGuid({0})&apos; method instead of comparing the GUID &apos;{0}&apos; with {1}, as this will result in a runtime error..
        /// </summary>
        internal static string GuidEmptyStringComparisonMessageFormat {
            get {
                return ResourceManager.GetString("GuidEmptyStringComparisonMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IsNullGuid() to check for empty GUID values..
        /// </summary>
        internal static string GuidEmptyStringComparisonTitle {
            get {
                return ResourceManager.GetString("GuidEmptyStringComparisonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;IsHandled&apos; parameter must always be set to &apos;true&apos; when handled. Avoid assigning &apos;false&apos; or any value that may be evaluated as false..
        /// </summary>
        internal static string IsHandledParameterAssignmentDescription {
            get {
                return ResourceManager.GetString("IsHandledParameterAssignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not set the &apos;IsHandled&apos; parameter to &apos;false&apos; or any value that may be evaluated as false..
        /// </summary>
        internal static string IsHandledParameterAssignmentMessageFormat {
            get {
                return ResourceManager.GetString("IsHandledParameterAssignmentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect &apos;IsHandled&apos; parameter assignment..
        /// </summary>
        internal static string IsHandledParameterAssignmentTitle {
            get {
                return ResourceManager.GetString("IsHandledParameterAssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace double quotes (&quot;) with two single quotes (&apos;&apos;).
        /// </summary>
        internal static string JsonTokenJPathUsesDoubleQuotesCodeAction {
            get {
                return ResourceManager.GetString("JsonTokenJPathUsesDoubleQuotesCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detects and warns against the use of double-quote (&quot;) characters in JPath expressions..
        /// </summary>
        internal static string JsonTokenJPathUsesDoubleQuotesDescription {
            get {
                return ResourceManager.GetString("JsonTokenJPathUsesDoubleQuotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double quote character detected in JPath expression. Replace all double quotes (&quot;) with two single quotes (&apos;&apos;)..
        /// </summary>
        internal static string JsonTokenJPathUsesDoubleQuotesMessageFormat {
            get {
                return ResourceManager.GetString("JsonTokenJPathUsesDoubleQuotesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use two single quotes instead of double quotes in JPath expressions.
        /// </summary>
        internal static string JsonTokenJPathUsesDoubleQuotesTitle {
            get {
                return ResourceManager.GetString("JsonTokenJPathUsesDoubleQuotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List objects are 1-based, meaning indexing starts from 1 instead of the conventional 0..
        /// </summary>
        internal static string ListObjectsAreOneBasedDescription {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List objects are 1-based.
        /// </summary>
        internal static string ListObjectsAreOneBasedMessageFormat {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero index access on 1-based List objects.
        /// </summary>
        internal static string ListObjectsAreOneBasedTitle {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Add missing fields.
        /// </summary>
        internal static string MandatoryFieldMissingOnApiPageCodeAction {
            get {
                return ResourceManager.GetString("MandatoryFieldMissingOnApiPageCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API pages must expose a minimal set of mandatory system fields to ensure correct identification, change tracking, and webhook support..
        /// </summary>
        internal static string MandatoryFieldMissingOnApiPageDescription {
            get {
                return ResourceManager.GetString("MandatoryFieldMissingOnApiPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Field &apos;Rec.{0}&apos; exposed with the name &apos;{1}&apos; should always be included on API Pages.&quot;.
        /// </summary>
        internal static string MandatoryFieldMissingOnApiPageMessageFormat {
            get {
                return ResourceManager.GetString("MandatoryFieldMissingOnApiPageMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory fields must be exposed on API pages..
        /// </summary>
        internal static string MandatoryFieldMissingOnApiPageTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldMissingOnApiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataKeyFields property defines the unique and stable key for OData exposure. Using SystemId is strongly recommended because it is immutable and guaranteed not to change over the lifetime of a record. Using other fields can lead to unstable OData URLs, broken integrations, and data consistency issues..
        /// </summary>
        internal static string ODataKeyFieldsShouldUseSystemIdDescription {
            get {
                return ResourceManager.GetString("ODataKeyFieldsShouldUseSystemIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataKeyFields property is set to &apos;{0}&apos;, but should use the SystemId field..
        /// </summary>
        internal static string ODataKeyFieldsShouldUseSystemIdMessageFormat {
            get {
                return ResourceManager.GetString("ODataKeyFieldsShouldUseSystemIdMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODataKeyFields property should use the SystemId field..
        /// </summary>
        internal static string ODataKeyFieldsShouldUseSystemIdTitle {
            get {
                return ResourceManager.GetString("ODataKeyFieldsShouldUseSystemIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Wrap filter expression in StrSubstNo().
        /// </summary>
        internal static string OperatorAndPlaceholderInFilterExpressionCodeAction {
            get {
                return ResourceManager.GetString("OperatorAndPlaceholderInFilterExpressionCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule validates filter expressions passed to Record.SetFilter when placeholders (%1, %2, …) are used together with certain operators such as *, @, and ?. When these operators are included directly in the filter string, placeholders are not substituted as expected, leading to incorrect or unpredictable filtering results..
        /// </summary>
        internal static string OperatorAndPlaceholderInFilterExpressionDescription {
            get {
                return ResourceManager.GetString("OperatorAndPlaceholderInFilterExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found operator &apos;{0}&apos; together with placeholder &apos;{1}&apos; in filter expression, which results in unexpected behavior. Use the StrSubstNo() method to circumvent this..
        /// </summary>
        internal static string OperatorAndPlaceholderInFilterExpressionMessageFormat {
            get {
                return ResourceManager.GetString("OperatorAndPlaceholderInFilterExpressionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid unsupported operators with placeholders in SetFilter expressions.
        /// </summary>
        internal static string OperatorAndPlaceholderInFilterExpressionTitle {
            get {
                return ResourceManager.GetString("OperatorAndPlaceholderInFilterExpressionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule validates that record arguments passed to page-related operations match the page&apos;s SourceTable..
        /// </summary>
        internal static string PageRecordArgumentMismatchDescription {
            get {
                return ResourceManager.GetString("PageRecordArgumentMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0}: cannot convert from {1} to {2}..
        /// </summary>
        internal static string PageRecordArgumentMismatchMessageFormat {
            get {
                return ResourceManager.GetString("PageRecordArgumentMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page record argument does not match source table.
        /// </summary>
        internal static string PageRecordArgumentMismatchTitle {
            get {
                return ResourceManager.GetString("PageRecordArgumentMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling these methods on a page without a SourceTable results in invalid or unpredictable runtime behavior, because the page has no table context to operate on..
        /// </summary>
        internal static string PageRecordMethodRequiresSourceTableDescription {
            get {
                return ResourceManager.GetString("PageRecordMethodRequiresSourceTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceTable property is not defined on Page &apos;{0}&apos;. Method &apos;{1}&apos; requires a SourceTable..
        /// </summary>
        internal static string PageRecordMethodRequiresSourceTableMessageFormat {
            get {
                return ResourceManager.GetString("PageRecordMethodRequiresSourceTableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page record methods require a SourceTable.
        /// </summary>
        internal static string PageRecordMethodRequiresSourceTableTitle {
            get {
                return ResourceManager.GetString("PageRecordMethodRequiresSourceTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Add MaxLength property to Label declaration.
        /// </summary>
        internal static string PossibleOverflowAssigningAppendMaxLengthToLabelCodeAction {
            get {
                return ResourceManager.GetString("PossibleOverflowAssigningAppendMaxLengthToLabelCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Refactor by wrapping with Text.CopyStr(...).
        /// </summary>
        internal static string PossibleOverflowAssigningApplyCopyStrCodeAction {
            get {
                return ResourceManager.GetString("PossibleOverflowAssigningApplyCopyStrCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports cases where a Text/Label (or a computed Text such as concatenation) can exceed the maximum length of the target type (e.g., assigning to Code[20], Text[10], or a field with a smaller MaxLength)..
        /// </summary>
        internal static string PossibleOverflowAssigningDescription {
            get {
                return ResourceManager.GetString("PossibleOverflowAssigningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible overflow assigning &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string PossibleOverflowAssigningMessageFormat {
            get {
                return ResourceManager.GetString("PossibleOverflowAssigningMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible overflow when assigning text to a smaller target type..
        /// </summary>
        internal static string PossibleOverflowAssigningTitle {
            get {
                return ResourceManager.GetString("PossibleOverflowAssigningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule ensures that calls to the built-in .Get() procedure on Record objects have the correct number and types of arguments matching the primary key (PK) of the record in question..
        /// </summary>
        internal static string RecordGetProcedureArgumentsDescription {
            get {
                return ResourceManager.GetString("RecordGetProcedureArgumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments in .Get() method for record &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string RecordGetProcedureArgumentsMessageFormat {
            get {
                return ResourceManager.GetString("RecordGetProcedureArgumentsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number or type of arguments in .Get() method on Record object.
        /// </summary>
        internal static string RecordGetProcedureArgumentsTitle {
            get {
                return ResourceManager.GetString("RecordGetProcedureArgumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace SetRange with SetFilter.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsCodeAction {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is intended for simple value-based range filtering. When filter operators such as &lt;&gt;, .., *, &amp;, or | are used, the call represents a filter expression and may lead to unintended behavior. In such cases, SetFilter must be used to express the filter explicitly and correctly..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsDescription {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is called with a filter expression. Use SetFilter instead..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsMessageFormat {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter operators should not be used in SetRange.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsTitle {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field with table relation should have at least the same length as the referenced field..
        /// </summary>
        internal static string TableRelationFieldLengthDescription {
            get {
                return ResourceManager.GetString("TableRelationFieldLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related field has length {0} ({1}) which is longer than the current field length {2} ({3}).
        /// </summary>
        internal static string TableRelationFieldLengthMessageFormat {
            get {
                return ResourceManager.GetString("TableRelationFieldLengthMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table relation field length mismatch.
        /// </summary>
        internal static string TableRelationFieldLengthTitle {
            get {
                return ResourceManager.GetString("TableRelationFieldLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing table triggers (Insert, Modify, Delete, DeleteAll, ModifyAll) or calling Validate on temporary record variables causes the temporary scope to be lost. This can result in unintended database changes because the record is no longer treated as temporary. Only execute triggers when the table itself is defined as temporary. .
        /// </summary>
        internal static string TemporaryRecordTriggerInvocationDescription {
            get {
                return ResourceManager.GetString("TemporaryRecordTriggerInvocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not execute table triggers or validation methods on temporary record variables..
        /// </summary>
        internal static string TemporaryRecordTriggerInvocationMessageFormat {
            get {
                return ResourceManager.GetString("TemporaryRecordTriggerInvocationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid triggering table logic on temporary records.
        /// </summary>
        internal static string TemporaryRecordTriggerInvocationTitle {
            get {
                return ResourceManager.GetString("TemporaryRecordTriggerInvocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same field ID is used with different field names in tables coupled via TransferFields. While this does not cause a runtime error, it increases the risk of accidental coupling of fields with different intent..
        /// </summary>
        internal static string TransferFieldsNameMismatchDescription {
            get {
                return ResourceManager.GetString("TransferFieldsNameMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with ID {0} resolves to different field names ({3} ≠ {4}) between TransferFields-coupled tables {1} and {2}..
        /// </summary>
        internal static string TransferFieldsNameMismatchMessageFormat {
            get {
                return ResourceManager.GetString("TransferFieldsNameMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent field names across TransferFields.
        /// </summary>
        internal static string TransferFieldsNameMismatchTitle {
            get {
                return ResourceManager.GetString("TransferFieldsNameMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables coupled via TransferFields must define matching field types for the same field ID. A type mismatch will result in a runtime error when TransferFields is executed, as incompatible field types cannot be safely copied..
        /// </summary>
        internal static string TransferFieldsTypeMismatchDescription {
            get {
                return ResourceManager.GetString("TransferFieldsTypeMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields {5} and {6} with ID {0} have a possible incompatible field type ({3} → {4}) between TransferFields-coupled tables {1} and {2}..
        /// </summary>
        internal static string TransferFieldsTypeMismatchMessageFormat {
            get {
                return ResourceManager.GetString("TransferFieldsTypeMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible field types across TransferFields.
        /// </summary>
        internal static string TransferFieldsTypeMismatchTitle {
            get {
                return ResourceManager.GetString("TransferFieldsTypeMismatchTitle", resourceCulture);
            }
        }
    }
}
