//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.PlatformCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlatformCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.PlatformCop.PlatformCopAnalyzers", typeof(PlatformCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every AL object should explicitly specify its Access property to make its intended accessibility clear. Explicitly setting Access prevents accidental exposure or over-restriction of objects and forces conscious design decisions about visibility..
        /// </summary>
        internal static string AccessPropertyExplicitlySetDescription {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; does not explicitly have the Access property set..
        /// </summary>
        internal static string AccessPropertyExplicitlySetMessageFormat {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every object needs to specify a value for the Access property.
        /// </summary>
        internal static string AccessPropertyExplicitlySetTitle {
            get {
                return ResourceManager.GetString("AccessPropertyExplicitlySetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoCalcFields should only be used for FlowFields or Blob fields.
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsDescription {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AutoCalcFields method should only be used with FlowFields or fields of type Blob. The field {0} is not a FlowField or of type Blob..
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsMessageFormat {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoids a runtime error from using AutoCalcFields on a field that is not a FlowField or a field of type Blob..
        /// </summary>
        internal static string AutoCalcFieldsOnlyOnFlowFieldsTitle {
            get {
                return ResourceManager.GetString("AutoCalcFieldsOnlyOnFlowFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement relies on SQL Server to generate the next value when inserting records. Temporary tables are only in-memory in Business Central and are not created on SQL Server, so SQL Server cannot generate AutoIncrement values. This results in runtime failures when code inserts into the temporary table..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableDescription {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement is used in a table with TableType = Temporary, which will cause a runtime error. Remove AutoIncrement or make the table non-temporary..
        /// </summary>
        internal static string AutoIncrementInTemporaryTableMessageFormat {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoIncrement fields are not supported in temporary tables.
        /// </summary>
        internal static string AutoIncrementInTemporaryTableTitle {
            get {
                return ResourceManager.GetString("AutoIncrementInTemporaryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Editable property to False.
        /// </summary>
        internal static string EditableFlowFieldCodeAction {
            get {
                return ResourceManager.GetString("EditableFlowFieldCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields are calculated fields whose values are derived from other data and are not stored on the record itself. Allowing a FlowField to be editable exposes an input surface that the platform does not process by default. User-entered values are neither validated nor persisted unless custom logic is explicitly implemented..
        /// </summary>
        internal static string EditableFlowFieldDescription {
            get {
                return ResourceManager.GetString("EditableFlowFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is editable, which is uncommon for a FlowField. Set Editable = false, or add a comment to justify why editing is intentional..
        /// </summary>
        internal static string EditableFlowFieldMessageFormat {
            get {
                return ResourceManager.GetString("EditableFlowFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable.
        /// </summary>
        internal static string EditableFlowFieldTitle {
            get {
                return ResourceManager.GetString("EditableFlowFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Set Extensible property to platform default.
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetCodeAction {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public objects should explicitly define their extensibility by setting the Extensible property to either true or false. Leaving this property unspecified relies on implicit defaults and can lead to avoidable compatibility and maintenance issues..
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetDescription {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property Extensible should be explicitly set for public objects..
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetMessageFormat {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicitly set Extensible property on public objects.
        /// </summary>
        internal static string ExtensiblePropertyExplicitlySetTitle {
            get {
                return ResourceManager.GetString("ExtensiblePropertyExplicitlySetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List objects are 1-based, meaning indexing starts from 1 instead of the conventional 0..
        /// </summary>
        internal static string ListObjectsAreOneBasedDescription {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List objects are 1-based.
        /// </summary>
        internal static string ListObjectsAreOneBasedMessageFormat {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero index access on 1-based List objects.
        /// </summary>
        internal static string ListObjectsAreOneBasedTitle {
            get {
                return ResourceManager.GetString("ListObjectsAreOneBasedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Replace SetRange with SetFilter.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsCodeAction {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is intended for simple value-based range filtering. When filter operators such as &lt;&gt;, .., *, &amp;, or | are used, the call represents a filter expression and may lead to unintended behavior. In such cases, SetFilter must be used to express the filter explicitly and correctly..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsDescription {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRange is called with a filter expression. Use SetFilter instead..
        /// </summary>
        internal static string SetRangeWithFilterOperatorsMessageFormat {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter operators should not be used in SetRange.
        /// </summary>
        internal static string SetRangeWithFilterOperatorsTitle {
            get {
                return ResourceManager.GetString("SetRangeWithFilterOperatorsTitle", resourceCulture);
            }
        }
    }
}
