//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.FormattingCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormattingCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormattingCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.FormattingCop.FormattingCopAnalyzers", typeof(FormattingCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALCops: Fix casing.
        /// </summary>
        internal static string CasingMismatchCodeAction {
            get {
                return ResourceManager.GetString("CasingMismatchCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although incorrect casing is syntactically valid, it is not common practice and reduces readability and recognizability of code..
        /// </summary>
        internal static string CasingMismatchDescription {
            get {
                return ResourceManager.GetString("CasingMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Help improving this rule and open a GitHub issue, pretty please? :-).
        /// </summary>
        internal static string CasingMismatchImproveDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("CasingMismatchImproveDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;{0}&apos; instead of &apos;{1}&apos; for consistent casing..
        /// </summary>
        internal static string CasingMismatchMessageFormat {
            get {
                return ResourceManager.GetString("CasingMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casing of symbols and keywords must align with the language definition.
        /// </summary>
        internal static string CasingMismatchTitle {
            get {
                return ResourceManager.GetString("CasingMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In AL the semicolon is a statement separator, not a terminator, and procedure or trigger signatures do not require a semicolon at the end. Although the compiler accepts it, enforcing this rule improves consistency and aligns with the coding guidelines used by the community..
        /// </summary>
        internal static string SemicolonAfterMethodOrTriggerDeclarationDescription {
            get {
                return ResourceManager.GetString("SemicolonAfterMethodOrTriggerDeclarationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} declaration ends with a semicolon. Remove the trailing semicolon from the declaration..
        /// </summary>
        internal static string SemicolonAfterMethodOrTriggerDeclarationMessageFormat {
            get {
                return ResourceManager.GetString("SemicolonAfterMethodOrTriggerDeclarationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure or Trigger declaration should not end with semicolon.
        /// </summary>
        internal static string SemicolonAfterMethodOrTriggerDeclarationTitle {
            get {
                return ResourceManager.GetString("SemicolonAfterMethodOrTriggerDeclarationTitle", resourceCulture);
            }
        }
    }
}
