<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
        <TargetFrameworks Condition="'$(ContinuousIntegrationBuild)' != 'true'">net10.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(ContinuousIntegrationBuild)' == 'true'">netstandard2.1;net8.0;net10.0</TargetFrameworks>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

        <!-- Path to BC dev tools may be overridden by /p:BcDevToolsDir= -->
        <BcDevToolsDir Condition="'$(BcDevToolsDir)'==''">../../Microsoft.Dynamics.BusinessCentral.Development.Tools</BcDevToolsDir>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Update="ALCops.TestAutomationCopAnalyzers.resx">
            <LogicalName>ALCops.TestAutomationCop.TestAutomationCopAnalyzers.resources</LogicalName>
            <Generator>MSBuild:Compile</Generator>
            <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
            <StronglyTypedNamespace>ALCops.TestAutomationCop</StronglyTypedNamespace>
            <StronglyTypedFileName>$(IntermediateOutputPath)ALCops.TestAutomationCopAnalyzers.cs</StronglyTypedFileName>
            <StronglyTypedClassName>TestAutomationCopAnalyzers</StronglyTypedClassName>
        </EmbeddedResource>
        <Compile Include="$(IntermediateOutputPath)ALCops.TestAutomationCopAnalyzers.cs"
                 Condition="'$(DesignTimeBuild)' == 'true' and Exists('$(IntermediateOutputPath)ALCops.TestAutomationCopAnalyzers.cs')"
                 Visible="false">
            <AutoGen>true</AutoGen>
            <DesignTime>true</DesignTime>
            <DependentUpon>ALCops.TestAutomationCopAnalyzers.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="../ALCops.Common/ALCops.Common.csproj" />
    </ItemGroup>

    <!-- BC Dev Tools -->
    <ItemGroup>
        <Reference Include="Microsoft.Dynamics.Nav.CodeAnalysis">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/Microsoft.Dynamics.Nav.CodeAnalysis.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="System.Composition.AttributedModel">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>$(BcDevToolsDir)/$(TargetFramework)/System.Composition.AttributedModel.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <!-- Legacy support for netstandard2.1 -->
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Collections.Immutable" />
    </ItemGroup>
</Project>