//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.DocumentationCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentationCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.DocumentationCop.DocumentationCopAnalyzers", typeof(DocumentationCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Commit() manually interrupts the default transactional behavior of Business Central by persisting changes earlier than the platform would normally allow. Although there are valid use cases, the reason cannot be inferred from the code itself. A leading or trailing comment is required to document why the commit is necessary..
        /// </summary>
        internal static string CommitRequiresCommentDescription {
            get {
                return ResourceManager.GetString("CommitRequiresCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() needs a comment to justify its existence. Add a leading or trailing comment explaining why it is required..
        /// </summary>
        internal static string CommitRequiresCommentFormat {
            get {
                return ResourceManager.GetString("CommitRequiresCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() needs a comment to justify its existence.
        /// </summary>
        internal static string CommitRequiresCommentTitle {
            get {
                return ResourceManager.GetString("CommitRequiresCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields are calculated fields and are not intended to be written to. Writing to a FlowField, whether accidental or intentional, can lead to runtime errors..
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentDescription {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to a FlowField is not common and requires a comment explaining why this assignment is intentional..
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentFormat {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to FlowFields is not common and requires an explanatory comment.
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentTitle {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentTitle", resourceCulture);
            }
        }
    }
}
