//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.DocumentationCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentationCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.DocumentationCop.DocumentationCopAnalyzers", typeof(DocumentationCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Commit() manually interrupts the default transactional behavior of Business Central by persisting changes earlier than the platform would normally allow. Although there are valid use cases, the reason cannot be inferred from the code itself. A leading or trailing comment is required to document why the commit is necessary..
        /// </summary>
        internal static string CommitRequiresCommentDescription {
            get {
                return ResourceManager.GetString("CommitRequiresCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() needs a comment to justify its existence. Add a leading or trailing comment explaining why it is required..
        /// </summary>
        internal static string CommitRequiresCommentMessageFormat {
            get {
                return ResourceManager.GetString("CommitRequiresCommentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() needs a comment to justify its existence.
        /// </summary>
        internal static string CommitRequiresCommentTitle {
            get {
                return ResourceManager.GetString("CommitRequiresCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty statements (standalone ;) reduce readability and are commonly introduced by mistake. This rule flags empty statement expressions (excess semicolons) so they can be removed..
        /// </summary>
        internal static string EmptyStatementRequiresCommentDescription {
            get {
                return ResourceManager.GetString("EmptyStatementRequiresCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty statements should be removed or have a leading or trailing comment explaining why it is intentionally empty..
        /// </summary>
        internal static string EmptyStatementRequiresCommentMessageFormat {
            get {
                return ResourceManager.GetString("EmptyStatementRequiresCommentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty statements should be removed or documented.
        /// </summary>
        internal static string EmptyStatementRequiresCommentTitle {
            get {
                return ResourceManager.GetString("EmptyStatementRequiresCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public procedures are part of the exposed API and must be explicitly documented to justify their availability. XML documentation comments communicate intent, usage, and guarantees to consumers of the extension..
        /// </summary>
        internal static string PublicProcedureRequiresDocumentationDescription {
            get {
                return ResourceManager.GetString("PublicProcedureRequiresDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public procedure &apos;{0}&apos; must have XML documentation (or be restricted to local or internal scope)..
        /// </summary>
        internal static string PublicProcedureRequiresDocumentationMessageFormat {
            get {
                return ResourceManager.GetString("PublicProcedureRequiresDocumentationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public procedures must have XML documentation.
        /// </summary>
        internal static string PublicProcedureRequiresDocumentationTitle {
            get {
                return ResourceManager.GetString("PublicProcedureRequiresDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields are calculated fields and are not intended to be written to. Writing to a FlowField, whether accidental or intentional, can lead to runtime errors..
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentDescription {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to a FlowField is not common and requires a comment explaining why this assignment is intentional..
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentMessageFormat {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to FlowFields is not common and requires an explanatory comment.
        /// </summary>
        internal static string WriteToFlowFieldRequiresCommentTitle {
            get {
                return ResourceManager.GetString("WriteToFlowFieldRequiresCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML documentation for a procedure must accurately reflect its signature..
        /// </summary>
        internal static string XmlDocumentationProcedureConsistencyDescription {
            get {
                return ResourceManager.GetString("XmlDocumentationProcedureConsistencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML documentation does not match the procedure signature..
        /// </summary>
        internal static string XmlDocumentationProcedureConsistencyMessageFormat {
            get {
                return ResourceManager.GetString("XmlDocumentationProcedureConsistencyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML documentation must match the procedure signature.
        /// </summary>
        internal static string XmlDocumentationProcedureConsistencyTitle {
            get {
                return ResourceManager.GetString("XmlDocumentationProcedureConsistencyTitle", resourceCulture);
            }
        }
    }
}
